<%@ Page Title="" Language="C#" MasterPageFile="~/Home.master" AutoEventWireup="true" CodeFile="Home.aspx.cs" Inherits="Home" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <html>
<head>
	<title>Image carousel generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Image carousel" />
	
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->

</head>
<body>
	
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
		<li><img src="data1/images/investmentstratedgy.jpg" alt="investment-stratedgy" title="" id="wows1_0"/></li>
		<li><img src="data1/images/1.jpg" alt="1" title="" id="wows1_1"/></li>
		<li><img src="data1/images/8.jpg" alt="8" title="" id="wows1_2"/></li>
		<li><img src="data1/images/finance_bill_1600x900.jpg" alt="Finance bill 1600x900" title="" id="wows1_3"/></li>
		<li><img src="data1/images/getfinancialhelpwithsimplefreeinvestmenttoolsonline.jpg" alt="Get-Financial-Help-with-Simple-Free-Investment-Tools-Online" title="" id="wows1_4"/></li>
		<li><a href="http://wowslider.com/vf"><img src="data1/images/handshakehd.jpg" alt="full screen slider" title="" id="wows1_5"/></a></li>
		<li><img src="data1/images/hdvestlaunchestaxanalysistoolforadvisers.jpgmaxw=1000q=90cci_ts=20140521153442.jpg" alt="-HD-Vest-launches-tax-analysis-tool-for-advisers.jpg&maxw=1000&q=90&cci_ts=20140521153442" title=""/></li>
	</ul></div>
<span class="wsl"><a href="http://wowslider.com/vu">image carousel</a> by WOWSlider.com v7.4</span>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->

</body>
</html>
   
</asp:Content>

