<%@ Page Title="" Language="C#" MasterPageFile="~/rent.master" AutoEventWireup="true" CodeFile="Home.aspx.cs" Inherits="Home" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

  
    <html>
<head>
	<title>Image carousel generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Image carousel" />
	
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->

</head>
<body>
	
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
		<li><img src="data1/images/im1.jpg" alt="im1" title="im1" id="wows1_0"/></li>
		<li><img src="data1/images/im2.jpg" alt="im2" title="im2" id="wows1_1"/></li>
		<li><img src="data1/images/im3.jpg" alt="im3" title="im3" id="wows1_2"/></li>
		<li><img src="data1/images/im4.jpg" alt="im4" title="im4" id="wows1_3"/></li>
		<li><img src="data1/images/im5.jpg" alt="im5" title="im5" id="wows1_4"/></li>
		<li><img src="data1/images/im6.jpg" alt="im6" title="im6" id="wows1_5"/></li>
		<li><img src="data1/images/im7.jpg" alt="im7" title="im7" id="wows1_6"/></li>
		<li><a href="http://wowslider.com/vf"><img src="data1/images/im8.jpg" alt="full screen slider" title="full screen slider" id="wows1_7"/></a></li>
		<li><img src="data1/images/im9.jpg" alt="im9" title="im9" id="wows1_8"/></li>
	</ul></div>
	<div class="ws_bullets"><div>
		<a href="#" title="im1"><img src="data1/tooltips/im1.jpg" alt="im1"/>1</a>
		<a href="#" title="im2"><img src="data1/tooltips/im2.jpg" alt="im2"/>2</a>
		<a href="#" title="im3"><img src="data1/tooltips/im3.jpg" alt="im3"/>3</a>
		<a href="#" title="im4"><img src="data1/tooltips/im4.jpg" alt="im4"/>4</a>
		<a href="#" title="im5"><img src="data1/tooltips/im5.jpg" alt="im5"/>5</a>
		<a href="#" title="im6"><img src="data1/tooltips/im6.jpg" alt="im6"/>6</a>
		<a href="#" title="im7"><img src="data1/tooltips/im7.jpg" alt="im7"/>7</a>
		<a href="#" title="full screen slider"><img src="data1/tooltips/im8.jpg" alt="full screen slider"/>8</a>
		<a href="#" title="im9"><img src="data1/tooltips/im9.jpg" alt="im9"/>9</a>
	</div></div><span class="wsl"><a href="http://wowslider.com/vu">image carousel</a> by WOWSlider.com v7.4</span>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->

</body>
</html>

</asp:Content>

